---
title: "t-критерии"
author: "Ваша фамилия"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Введение

В этом задании вы сможете попрактиковаться в применении t-критериев для проверки статистических гипотез.

Данные были собраны Paul Cortez и Alice Silva путем опроса, проведенного среди учеников португальских школ. Были собраны основные социальные и демографические данные, а также данные успеваемости каждого ученика. Позже набор данных стал частью репозитория машинного обучения UCI благодаря исследователям Fabio Pagnotta и Hossain Mohammad. Информация о наборе данных доступна по ссылке: [здесь](https://archive.ics.uci.edu/ml/datasets/STUDENT+ALCOHOL+CONSUMPTION) или [здесь](http://archive.ics.uci.edu/ml/datasets/student+performance).
Рекомендуется ознакомиться со статьей, приложенной к набору данных на сайте, чтобы получить представление о методологии сбора данных и интерпретации авторов.

Для использования в этом задании, было выбрано подмножество изначальных данных, оно доступно в файле [student-mat.xlsx](student-mat.xlsx). Файл содержит данные об успеваемости слушателей по математике. Коды для категориальных переменных были заменены текстовыми метками для упрощения интерпретации.

## Информация об атрибутах:

- `school` - школа
- `sex` - пол школьника (`F` - женский и `M` - мужской)
- `age` - возраст школьника (числовой: от `15` до `22`)
- `address` - тип адреса школьника (`urban` (городской) или `rural` (сельский))
- `famsize` - размер семьи (`3 or less`, `4 or more`)
- `Pstatus` - родительский статус сожительства (`living together` или `living apart`)
- `Medu` - образование матери (упорядоченный: от `0 - none` до `4 - higher education`)
- `Fedu` - образование отца (также, как и в `Medu`)
- `Mjob` - работа матери (номинальный: `teacher`, `health` работники здравоохранения, гуманитарные `services` (например, административный работник или полицейский), `at_home` или `other`)
-  `Fjob` - работа отца (также, как и в `Mjob`)
- `reason` - причина выбора школы (номинальный: близость к дому `home`, репутация школы `reputation`, `course` предпочтение курсу или `other`)
- `guardian` - опекун студента (номинальный: `mother`, `father` или `other`)
- `traveltime` - время пути от школы до дома (упорядоченный: `1 - <15 min.`, `2 - 15 to 30 min.`, `3 - 30 min. to 1 hour`, или `4 - >1 hour`)
- `studytime` - количество часов обучения в неделю (упорядоченный: `1 - <2 hours`, `2 - 2 to 5 hours`, `3 - 5 to 10 hours`, или `4 - >10 hours`)
- `failures` - количество проваленных классов (числовой: n если 1<=n<3, иначе `4`)
- `schoolsup` - дополнительная образовательная подержка (да или нет)
- `famsup` - семейная образовательная поддержка (да или нет)
- `paid` - дополнительные платные курсы по предмету (математика) (да или нет)
- `activities` - внеклассные занятия (да или нет)
- `nursery` - было ли обучение в детском саду (да или нет)
- `higher` - есть желание к высшему образованию (да или нет)
- `internet` - доступ к интернету дома (да или нет)
- `romantic` - в романтических отношениях (да или нет)
- `famrel` - качество семейных отношений (упорядоченный: от `1 - very bad` до `5 - excellent`)
- `freetime` - свободное время после школы (упорядоченный: от `1 - very low` до `5 - very high`)
- `goout` - прогулки с друзьями (также, как и в `freetime`)
- `Dalc` - потребление алкоголя в будние дни (как в `freetime`)
- `Walc` - потребление алкоголя на выходных (как в `freetime`)
- `health` - текущий статус здоровья (упорядоченный: от `1 - very bad` до `5 - very good`)
- `absences` - количество прогулов (числовой: от `0` до `93`)
- `G1` - оценка за первый период (числовой: от `0` до `20`)
- `G2` - оценка за второй период (как в `G1`)
- `G3` - финальная оценка (как в `G1`)


# Задания

## Подготовка

Отберите только студентов школы `Gabriel Pereira` (`school`).
Добавьте в таблицу новую переменную `drink`, которая должна принимать значение `high` для школьников,  часто употребляющих алкоголь по выходным, и `low` для остальных. Часто употребляющими алкоголь будем считать школьников, у которых переменная `Walc` содержит высокий и очень высокий уровень потребления.



## 1. Сравнение оценок студентов в зависимости от потребления алкоголя

Верно ли, что студенты, часто употребляющие алкоголь по выходным, в среднем, получили более низкие оценки за первый семестр (`G1`), чем редко употребляющие алкоголь студенты?

Визуализируйте отличия в средних оценках с помощью ggplot2.
Проверьте гипотезу о равенстве средних оценок при помощи подходящего t-критерия.


## 2. Помогают ли платные курсы по математике улучшить оценки?

Рассмотрите студентов из группы часто употребляющих алкоголь по выходным, которые учились на дополнительных платных курсах по математике (`paid`). Помогло ли им посещение таких курсов улучшить оценки во втором семестре?

Визуализируйте отличия в оценках с помощью ggplot2.
Проверьте гипотезу о равенстве оценок при помощи подходящего t-критерия.

