---
title: "Сравнение точности методов прогнозирования"
author: "<ваше имя>"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Введение

В этом задании необходимо сравнить эффективность четырех методов прогнозирования: наивный прогноз, сезонный наивный прогноз, метод усреднения, метод дрейфа на примере показателя: `Реальная зарплата (WAG_M)` (из ЕАЭСД).

Выполните пункты задания, перечисленные ниже и ответьте на поставленные в задании вопросы.

Решения присылайте в HTML-формате на `postlogist@gmail.com`.

Задание можно делать в небольших группах (2-3 человека). Не забудьте указать авторов в заголовке документа.

------


# Задание

1. Загрузите из ЕАЭСД (sophist) показатель **Реальная зарплата (WAG_M)**
Разделите ряд на тестовый (последние 12 месяцев от имеющихся данных) и обучающий (данные с января 2010 года до начала тестового периода). 

2. Используя данные обучающего периода, постройте 4 простых модели прогнозирования (среднее, наивный и сезонный наивный прогноз, прогноз методом дрейфа). Разработайте прогноз на тестовый период.

3. Сравните и интерпретируйте показатели ошибки использованных методов прогнозирования:

 - на обучающем и тестовом периодах;
 - методом скользящего контроля (для этого метода можно использовать все данные).
 
4. Напишите вывод о том, какой метод оказался наиболее точным и почему?
