---
title: "Сравнение точности методов прогнозирования"
author: "<ваше имя>"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Введение

В этом задании необходимо сравнить эффективность четырех методов прогнозирования: наивный прогноз, сезонный наивный прогноз, метод усреднения, метод дрейфа на примере показателя: `Число перевозок пассажиров автобусами, млн чел.` (из Единого хранилища данных Москвы).
 
Выполните пункты задания, перечисленные ниже и ответьте на поставленные в задании вопросы.

Решения присылайте в HTML-формате на `postlogist@gmail.com`.

Задание можно делать в небольших группах (2 человека). Не забудьте указать авторов в заголовке документа.

------


# Задание

1. Сохраните данные из ЕХД ежемесячные значения показателя `Число перевозок пассажиров автобусами, млн чел.` за весь период наблюдений в файл Excel. [Ссылка](http://ehd.moscow/index.php?id_src=286&id_ind=2364&id_tab=1&action=show_details_open&show=inds&show_full=1&exist=1&source=-9999&id_root[0]=286_286&id_root[1]=286_2364).

2. Загрузите данные в R и сделайте из них временной ряд ts.

3. Разделите ряд на тестовый (последние 12 месяцев от имеющихся данных) и обучающий (глубину определите самостоятельно). 

4. Используя данные обучающего периода, постройте 4 простых модели прогнозирования (среднее, наивный и сезонный наивный прогноз, прогноз методом дрейфа). Разработайте прогноз на тестовый период.

5. Сравните и интерпретируйте показатели ошибки использованных методов прогнозирования:

 - на обучающем и тестовом периодах;
 - методом скользящего контроля (для этого метода можно использовать все данные).
 
6. Напишите вывод о том, какой метод оказался наиболее точным и почему?
