---
title: "Исследование данных об авиаперевозках"
author: "Здесь должна быть ваша фамилия"
date: '19 октября 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Описание набора данных

Набор данных [airports.zip](data/airports.zip) загружен с сайта [Министерства транспорта США](https://data.transportation.gov/Aviation/Consumer-Airfare-Report-Table-1a-All-U-S-Airport-P/tfrh-tu9e) и содержит информацию о	образуемых корреспондирующими аэропортами рынках транспортных услуг в США с 1993 по 2017 гг.

В наборе данных содержатся переменные:

 - tbl - название таблицы;

 - Year - год;	

 - quarter - квартал(=3 месяца); 	

 - citymarketid_1, citymarketid_2	- идентификационный номер рынка вылета и прилета, объединяющий несколько аэропортов, обслуживающих один и тот же город;

 - city1, city2	- город вылета и прилета;

 - airportid_1, airportid_2	- идентификационный номер аэропорта вылета и прилета, присвоенный Министерством транспорта США;

 - airport_1, airport_2	- код аэропорта вылета и прилета;

 - nsmiles	- расстояние прямого перелета (Non-Stop Market Miles); 

 - passengers	- количество пассажиров в день; 

 - fare	- общий средний тариф;

 - carrier_lg	- перевозчик с наибольшим тарифом;

 - large_ms	- доля рынка крупнейшего перевозчика;

 - fare_lg	- средний тариф крупнейшего перевозчика;

 - carrier_low - перевозчик с самым низким тарифом;	

 - lf_ms - доля рынка наименьшего перевозчика;

 - fare_low -	средний тариф наименьшего перевозчика;

 - Geocoded_City1, Geocoded_City2	- географическая широта и долгота города вылета и прилета; 
 
 - tbl1apk - уникальный идентификационный номер записи.
