---
title: "Исследование данных о хранилищах наливных грузов"
author: "Здесь должна быть ваша фамилия"
date: '11 октября 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Описание набора данных

Набор данных [bulk_storage.zip](data/bulk_storage.zip) загружен с [сайта штата Нью-Йорк](https://data.ny.gov/Energy-Environment/Bulk-Storage-Facilities-in-New-York-State/pteg-c78n) и содержит информацию о хранилищах наливных грузов в штате Нью-Йорк.

Набор данных имеет следующие столбцы:

 - Program Number	- идентификационный номер объекта;
 
 - Program Type	- тип (CBS - хранение химических веществ, PBS - хранение нефтепродуктов, MOSF - хранение нефти);

 - Site Type Name	- тип сооружения, где расположено хранилище;
 
 - Program Facility Name - название сооружения;
 
 - Address 1 - адрес или месторасположение сооружения;

 - Address 2 - дополнительная информация об адресе или месторасположении сооружения;

 - Locality	- ближайший город или деревня;
 
 - ZIP Code - почтовый индекс;	

 - County	- округ;
 
 - NYSDEC Region	- [регион NYSDEC](https://www.dec.ny.gov/about/50230.html);

 - Tank Number - номер резервуара (присваивается владельцем, может включать как буквы, так и цифры); 

 - Tank Location - физическое местонахождение резервуара (над землей, под землей и т.д.); 

 - Tank Status - статус резервуара;

 - Install Date	- дата установки резервуара, неизвестна, если значение отсутствует;

 - Capacity in Gallons - вместимость в галлонах;
 
 - Tank Type - строительный материал резервуара (в т.ч. FRP - Fiberglass Reinforced Plastic);

 - Close Date	- дата, когда резервуар был закрыт навсегда, неизвестна, если значение отсутствует;

 - Material Name - название вещества в резервуаре;
 
 - Percent - доля опасных веществ в резервуаре, %;
 
 - Expiration Date - дата, когда истекает сертификат или лицензия сооружения;
 
 - Site Status Name	- текущий статус сооружения;

 - UTMX	- географическая широта в системе координат UTM;

 - UTMY	- географическая долгота в системе координат UTM;

 - Location 1	- месторасположение на основе предоставленного адреса.
