---
title: "Исследование данных о транспортных инцидентах на железной дороге"
author: "Здесь должна быть ваша фамилия"
date: '19 октября 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

#Описание набора данных

Набор данных [incidents.zip](data/incidents.zip) загружен с [сайта Министерства транспорта США](https://data.transportation.gov/Railroads/Highway-Rail-Grade-Crossing-Incidents/4x4i-82hg) и содержит информацию о транспортных инцидентах, связанных с железнодорожными переездами и произошедших в США с 1975 по 2016 гг.

В наборе данных имеются следующие столбцы:

 - Reporting Railroad	- название конкретной железной дороги;

 - Reporting Railroad Code - код железной дороги;

 - Track Owner - владелец пути;	

 - Track Owner Code	- код владельца пути;

 - Highway User Speed	- скорость транспортного средства на шоссе;

 - Calendar Year - календарный год;

 - Fiscal Year - отчетный год;

 - CrossingID	- идентификационный номер ж-д переезда;

 - County	- округ;

 - Highway - шоссе;

 - DisplayDate	- дата происшествия;

 - Highway User Type - 	тип транспортного средства на шоссе;

 - Rail Equipment Type	- тип транспортного средства на железной дороге;

 - Carrying Hazmat - перевозились ли опасные грузы одним из участников ДТП;

 - Releasing Hazmat	- произошел ли выброс опасных грузов в результате ДТП;

 - Display Time	- время происшествия;

 - id	- идентификационный номер инцидента;

 - nonsuicidefatality	- количество погибших;

 - nonsuicideinjury	- количество пострадавших;

 - City	- город;

 - State Name	- штат;

 - Longitude	- географическая долгота;

 - Latitude - географическая широта;
 
 - GeoLocation - местоположение.
