---
title: "Исследование данных о продажах алкоголя."
author: "Здесь должна быть ваша фамилия"
date: '11 октября 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Описание набора данных

Набор данных [sales.zip](data/sales.zip) загружен с сайта [округа Montgomery (Washington, DC)](https://data.montgomerycountymd.gov/Community-Recreation/Warehouse-and-Retail-Sales/v76h-r7br) и содержит информацию о ежемесячных продажах и перемещениях алкогольной продукции нескольких категорий в данном округе за 2017-2018 годы.

Набор данных имеет следующие столбцы:

 - YEAR - год; 
 
 - MONTH - месяц;
 
 - SUPPLIER - название поставщика продукции;
 
 - ITEM.CODE - код продукта;	

 - ITEM.DESCRIPTION	- описание продукта;
 
 - ITEM.TYPE - тип продукта;	

 - RETAIL.SALES	- количество продукции, проданной в алкогольных магазинах округа Монтгомери;

 - RETAIL.TRANSFERS - количество продукции, перемещенной в алкогольные магазины округа Монтгомери;

 - WAREHOUSE.SALES - количество продукции, проданной компаниям, лицензированным на продажу алкогольных напитков.