---
title: "Исследование данных о передовых технологиях в логистике и УЦП"
author: "Здесь должна быть ваша фамилия"
date: '19 октября 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

#Описание набора данных

Набор данных [technologies.zip](data/technologies.zip) загружен с [сайта Правительства Канады](https://open.canada.ca/data/en/dataset/82e3a885-b0a4-4d64-ab56-b37d8dbf6ac2) и содержит информацию о внедрении передовых технологий в области грузопереработки, цепей поставок и логистики в 2014 г. в Канаде.

Файл данных имеет следующие поля:

- GEO - географическая зона;

- Adoption.of.advanced.technologies - степень внедрения технологии;

- Type.of.advanced.technologies - тип передовой технологии;

- North.American.Industry.Classification.System..NAICS.. - Отрасль по классификатору Северной Америки (NAICS);

- Enterprise.size - размер предприятий;

- UOM - единицы измерения;

- VALUE - процент предприятий данной отрасли, размера и т.д., относящихся к указанной степени внедрения выбранной технологии, из всех подобных предприятий;

- STATUS - качество данных исследования, где:

    - A - отличное;

    - B - очень хорошее;

    - C - хорошее;

    - D - приемлемое;

    - E - использовать с осторожностью; 

    - F - данные слишком ненадежные для публикации; 

    - ... - не применимо;
  
    - p - предварительные данные; 

    - r - исправленные данные; 

    - x - данные скрыты для удовлетворения требований конфиденциальности закона о статистике;

    - t - стертые данные.


