---
title: "Исследование данных о школах, получающих транспортные услуги OPT"
author: "Здесь должна быть ваша фамилия"
date: '19 октября 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

#Описание набора данных

Набор данных [transportation_sites.zip](data/transportation_sites.zip) загружен с [Портала открытых данных Правительства США](https://catalog.data.gov/dataset/transportation-sites) и содержит информацию о местах (школах), получающих транспортные услуги OPT (Office of Pupil Transportation) около города Нью-Йорк и других городов с 2005 по 2018 гг.

Файл данных имеет следующие поля:

 - School_Year - учебный год;

 - OPT_Code	- уникальный идентификатор для места, получающего любую транспортную услугу от OPT. Код OPT представляет организацию в определенном месте; несколько кодов могут быть связаны с одним местом, но один код не может быть связан с несколькими местами;

 - Name - название места;
 
 - Affiliation - категория, отражающая принадлежность к религиозной (или не религиозной группе);

 - Site_Type - тип места (школа, офис и пр.);

 - Street_Address	- адресс;

 - City	- город;
 
 - State - штат;

 - Zip - почтовый индекс;

 - Longitude	- географическая долгота;

 - Latitude - географическая широта;

 - Door_To_Door_Service	- получает ли данное место услуги перевозки «от двери до двери» (некоторых учеников забирают лично из дома);
 
 - Stop_To_School_Service	- получает ли данное место услуги перевозки "от остановки до школы" (автобус забирает одного или нескольких учеников от остановки);
 
 - Common_Carrier_Svc_Metrocards	- выдает ли данное место (школа) Metro-карточки своим ученикам (похоже на социальные карты в Москве);

 - Site_Reimbursement - получает ли данное место (школа) возмещение за предоставление собственного автобуса ученикам, которые имеют право на перевозку. Небольшое количество школ заключают контракты с автобусной компанией или содержат собственные автобусы. OPT не предоставляет услуги в этих школах, но может возмещать расходы школ на проезд.
 
 - Mid_Day_Service - получает ли данное место (школа) услуги в середине дня (или школьные поездки, или перевозка учеников в места, входящие в их образовательную программу); 

 - D2D_Late_Day_Programs - получает ли данное место (школа) услуги перевозки  "от двери до двери" учеников, участвующих в программах продленного дня. Обычно такие услуги предоставляются школам, которые отпускают своих учеников до 16:30, но есть и несколько исключений;

 - S2S_Late_Day_Programs - получает ли данное место (школа) услуги перевозки  "от остановки до школы" учеников, участвующих в программах продленного дня. Обычно такие услуги предоставляются школам, которые отпускают своих учеников до 16:00, но есть и несколько исключений.
 