---
title: "Прогнозирование цены на дом в округе Кинг"
author: "Здесь должна быть ваша фамилия"
date: '27 февраля 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

#Описание набора данных

Набор данных [kc_house_data.csv](data/kc_house_data.csv) загружен с сайта [kaggle.com](https://www.kaggle.com/harlfoxem/housesalesprediction/data) и содержит информацию о ценах продажи домов в округе Кинг (King County, USA) в период с мая 2014 по май 2015 года.

Файл данных имеет следующие поля:
- id - идентификатор дома;  
- date - дата продажи дома;  
- price - цена продажи дома;  
- bedrooms - количество спальных комнат в доме;
- bathrooms - количество ванных комнат в доме;
- sqft_living - жилая площадь дома в футах;  
- sqft_lot - площадь участка в футах;  
- floors - количество этажей в доме;  
- waterfront - признак, имеет ли дом морские виды;  
- view - признак того, что дом был осмотрен;  
- condition - насколько хороши условия проживания в доме;  
- grade - общая оценка дома по системе оценивания, принятой в округе Кинг;  
- sqft_above - площадь дома без цокольного этажа в футах;  
- sqft_basement- площадь цокольного этажа в футах;  
- yr_built - год постройки;  
- yr_renovated - год ремонта;  
- zipcode - zip-код;  
- lat - координата широты;  
- long - координата долготы;  
- sqft_living15 - жилая площадь в 2015 году (после ремонта);  
- sqft_lot15 - площадь участка в 2015 году (после ремонта).