---
title: "Прогнозирование ожидаемой продолжительности жизни"
author: "Здесь должна быть ваша фамилия"
date: '28 февраля 2018 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

#Описание набора данных

Набор данных [life_expectancy.csv](data/life_expectancy.csv) загружен с сайта [kaggle.com](https://www.kaggle.com/kumarajarshi/life-expectancy-who/data) и содержит данные Всемирной организации здравоохранения об ожидаемой продолжительности жизни в различных странах мира и возможных влияющих на нее факторах.

Файл данных имеет следующие поля:
- Country - наименование страны;   
- Year - год;  
- Status - статус страны (развитая или развивающаяся);  
- Life expectancy - ожидаемая продолжительность жизни;  
- Adult Mortality - смертность среди взрослых (количество умерших в возрасте 15-60 лет на 1000 человек населения);  
- infant deaths - детская смертность на 1000 человек населения;  
- Alcohol - зафиксированный объем потребления чистого алкоголя на душу населения, литров;
- percentage expenditure - процент расходов на здравоохранение в ВВП;  
- Hepatitis B - охват прививками от гепатита B среди годовалых детей, %;  
- Measles - количество заболеваний корью на 1000 человек населения;  
- BMI - средний индекс массы тела населения;  
- under-five deaths - смертность детей до 5 лет на 1000 человек населения;  
- Polio - охват привиками от полиомиелита среди годовалых детей, %;  
- Total expenditure - процент государственных расходов на здравоохранение в государственных расходах;  
- Diphtheria - охват прививками от дифтерии среди годовалых детей, %;  
- HIV/AIDS - смертность от ВИЧ детей до 4 лет на 1000 человек;  
- GDP - ВВП на душу населения в долларах США;  
- Population - численность населения страны;  
- thinness 1-19 years - преобладание худобы среди детей и подростков 10-19 лет, %;  
- thinness 5-9 years - преобладание худобы среди детей 5-9 лет, %;  
- Income composition of resources - индекс человеческого развития на базе уровня доходов, от 0 до 1;  
- Schooling - количество лет обучения в школе.  


