```{r}
library(gapminder)
```

```{r}
library(openxlsx)
setwd("E:/R/")
# for writing a data.frame or list of data.frames to an xlsx file
write.xlsx(gapminder, 'gapminder.xlsx')
```

```{r fig.width=12, fig.height=5}


ggplot(data = gapminder, aes(x=gdpPercap, y=lifeExp, size = pop, colour = country)) +  
  geom_point(alpha = 0.7, show.legend = FALSE) +
  
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_grid(continent~year)
  
  #facet_wrap(~continent) +
  # Here comes the gganimate specific bits
#labs(x = NULL, y = NULL)
 # labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') 
 # transition_time(year) +
 # ease_aes('linear')

```

```{r fig.width=12, fig.height=5}

gapminder2 = filter(gapminder, year > '1960' & year < '1967' )

ggplot(data = gapminder2, aes(x=gdpPercap, y=lifeExp, size = pop, colour = country)) +  
  geom_point(alpha = 0.7, show.legend = FALSE) +
  
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent)

```



```{r}


ggplot(gapminder, aes(x=gdpPercap, y=lifeExp, size = pop, colour = country)) +
  
  geom_point(alpha = 0.7, show.legend = FALSE) +
  
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')
```






