```{r}
#suppressMessages(library(readr)) # считывание данных из текстовых файлов
suppressMessages(library(tidyverse)) # манипулирование данными
suppressMessages(library(ggplot2)) # визуализация
suppressMessages(library(scales)) # Процентный формат для осей графиков
suppressMessages(library(readxl))
```

https://r-analytics.blogspot.com/2012/03/t.html
https://www.youtube.com/watch?v=pTmLQvMM-1M

```{r}
data_seq <- read_excel('seq.xlsx') 
data_conv <- read_excel('conv.xlsx') 
set.seed(43)
```

```{r}
head(data_seq)
```

```{r}
data_seq <- data_seq %>%
  mutate ( scenario = "sequental") %>%
 rename( "stage_enter_time"= "stage_11_enter_time:", "delay_exit_time" = "delay_exit_time:") %>%
  mutate ( system_time = delay_exit_time - stage_enter_time )

#data_seq <- data_seq %>% sample_n(size = 200)

data_conv <- data_conv %>%
  mutate ( scenario = "conveyor") %>%
  rename( "stage_enter_time"= "stage_1_enter_time:", "delay_exit_time" = "delay_exit_time:") %>%
  mutate ( system_time = delay_exit_time - stage_enter_time )

#data_conv <- data_conv %>% sample_n(size = 200)

data_seq 
data_conv

```

```{r}
both_sets <- rbind(data_seq,data_conv)
both_sets
```

```{r}
ggplot(data = both_sets, aes(y = system_time, x = scenario, fill = scenario)) +
  geom_boxplot() +
  labs(title = 'Время в системе', x = NULL, y = NULL, fill = 'Сценарий')
```
https://stackoverflow.com/questions/17414565/interpretation-of-stat-summary-mean-cl-boot-at-ggplot2

```{r}
ggplot(data = both_sets, aes(x = scenario, y = system_time, color = scenario)) +
  stat_summary(fun.data=mean_cl_boot) +
  labs(title = paste('Среднее время в системе', 
                nrow(both_sets), 'наблюдениям' ),
       x = NULL, y = NULL, color = 'Сценарий')
```

```{r}
result <- t.test(system_time ~ scenario, data = both_sets)
result
```

