---
title: "Методы экспоненциального сглаживания II"
author: "<ваше имя>"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Введение

В этом задании необходимо построить несколько моделей прогнозирования для различных временных рядов из ЕАЭСД (sophist). 

Выполните пункты задания, перечисленные ниже и ответьте на поставленные в задании вопросы.

Решения присылайте в HTML-формате на `postlogist@gmail.com`.

Задание можно делать в небольших группах (2-3 человека). Не забудьте указать авторов в заголовке документа.

------

# Задания


## 1. Прогноз рождаемости и смертности в России по моделям с затухающим трендом


- Загрузите из ЕАЭСД (Sophist) данные по годовым показателям рождаемости ('POPFER_Y') и смертности ('POPMOR_Y') - в промилле (чел / 1000 чел населения)

- Сравните динамику этих покзателей на одном графике  

- Определите, какую часть данных следует использовать для построения моделей  

- Разделите данные на обучающий и тестовый (последние 5 лет) периоды  

- Для каждого показателя постройте модели с линейным, экспоненциальным, аддитивным затухающим и мультипликативным затухающим трендом (на обучающем периоде)  

- Сравните согласие моделей с фактом на тестовом периоде визуально и с помощью показателей ошибки  

- Выберите лучшую модель для каждого показателя  

- Перестройте лучшие модели с использованием всех данных и сделайте прогноз показателей рождаемости и смертности на следующие 5 лет  

- Визуализируйте свой прогноз


## Задание 2. Прогноз объемов импорта по моделям с затухающим трендом

- Загрузите из ЕАЭСД (Sophist) данные по ежемесячным объемам импорта ('IM_T_M') в млрд. долл.

- Визуализируйте динамику этого покзателя

- Определите, какую часть данных следует использовать для построения моделей

- Разделите данные на обучающий и тестовый (последний год) периоды

- Постройте модели с линейным, экспоненциальным, аддитивным затухающим и мультипликативным затухающим трендом (на обучающем периоде), используя функцию ets.

- Сравните согласие моделей с фактом на тестовом периоде визуально и с помощью показателей ошибки

- Выберите лучшую модель.

- Перестройте лучшую модель с использованием всех данных и сделайте прогноз показателя импорта на следующие 5 лет.

- Визуализируйте свой прогноз
