---
title: "Прогнозирование продаж строительных материалов"
author: "Ваши фамилии"
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

В файле [materials.csv](https://rawgit.com/postlogist/research-seminar/master/time-series/data/materials.csv) содержатся сведения о ежедневных продажах строительных товаров трех категорий: Грунтовка, Напольные покрытия и Сухие смеси.

Ваша задача - разработать прогноз на 12 месяцев по каждой товарной категории, используя пакет `sweep` и функцию `map`. Учтите, что исходные данные не являются временным рядом и необходимо преобразовать детальные данные о продажах в ряды ежемесячных продаж, прежде, чем начинать прогнозирование. Для прогнозирования можно использовать любую функцию из пакета `forecast`.

Дополнительно вы можете доработать свой код таким образом, чтобы он сравнивал для каждого ряда несколько моделей и строил прогноз только по лучшей из них.

Каждая из частей - основная и дополнительная - оцениваются как две активности. 

В решении необходимо использовать только функции семейства `map*()`, нельзя использовать циклы.

Решения присылайте на postlogist@gmail.com






