---
title: "Прогнозирование продаж с помощью регрессии"
author: "<поменяй меня!>"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Введение

В файле 'catalog.xlsx' содержится история продаж компании, торгующей по каталогу.

Переменные в наборе данных:

 - **date** - месяц продажи
 - **men** - продажи мужской одежды
 - **women** - продажи женской одежды
 - **jewel** - продажи украшений
 - **mail** - количество разосланных по почте каталогов
 - **page** - страниц в каталоге
 - **phone** - количество линий в контакт-центре для приема заказов
 - **printadv** - затраты на рекламу в средствах печати
 - **service** - количество торговых представителей
 
 
# Задание

1. Выберите любую товарную категорию (одежда для мужчин или женщин, либо украшения)

2. Проведите разведочный анализ с целью выявления факторов, влияющих на продажи этой категории

3. Разделите данные на обучающий и тестовый (последний год) период

4. Постройте модель множественной регрессии, включающей только тренд и сезонность для прогнозирования продаж. Исследуйте модель на адекватность. Оцените точность модели на тестовом периоде (на основе MAPE и BIAS). 

5. Постройте модель множественной регрессии, которая учитывает влияние факторов на продажи. Исследуйте модель на адекватность. Оцените точность модели на тестовом периоде (по тем же показателям)

6. Подготовьте отчет в формате HTML, содержащий описание построенных вами моделей и выводы (какую модель рекомендуете использовать для прогнозирования и почему).

Отчет присылайте на мой e-mail. Можно работать в группах (2-3 человека). При обнаружении плагиата работа будет аннулирована всем соучастникам.
