---
title: "Предсказание трудоустройства"
author: "Поменяй меня!"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
options(width = 100) # ширина текстового вывода
options(digits = 3) # число знаков после запятой в выводе
```

# Задание

В файле `Placement_Data_Full_Class.csv` содержится сведения о студентах магистерской образовательной программы, которые участвовали в программе трудоустройства, предложенной их университетом (campus placement program). Сведения содержат информацию об образовании и достигнутых результатах, опыте работы кандидатов. Целевая переменная - был ли трудоустроен студент (`status`). Вторая целевая переменная - зарплата кандидата (`salary`).  

Обратите внимание, что зарплата (`salary`) является целевой переменной и до собеседования неизвестна. Поэтому она не должна участвовать как предиктор ни в каких моделях, которые вы будете строить. Порядковый номер `sl_id` также не должен использоваться в моделях.

Источник: Kaggle,
https://www.kaggle.com/benroshan/factors-affecting-campus-placement


Требуется:

  1. Провести разведочный анализ для выявления факторов, влияющих на получение работы.  
  2. Разделить выборку на обучающее и тестовое множество (80/20)
  3. Построить на обучающем множестве модель дерева решений. Оценить ошибку модели на обучающем и тестовом множестве. Сравнить факторы успешного трудоустройства, выявленные моделью с факторами, которые вы нашли на этапе разведочного анализа. Сделать прогноз трудоустройства (Placed/Not Placed) и вероятности трудоустройства для тестового множества. Выведите ранжированный список из 20 студентов с наибольшей вероятностью трудоустройства в виде таблицы (таблица должна быть в HTML-отчете, используйте, например, функцию `knitr::kable()`, чтобы ее получить).
  4. Повторить анализ с моделью логистической регрессии. Постарайтесь получить как можно более точную модель. Дополнительно необходимо интерпретировать модель, указав, какие факторы увеличивают вероятность трудоустройства. 
  5. Сравните качество построенных вами моделей классификации на обучающем и тестовом множестве, интерпретируйте результаты и рекомендуйте лучшую модель.


**Описание переменных**

(Предыдущие переменные в анализе не требуются)
- sl_no: порядковый номер
- gender: пол студента (Male = M, Female = F)
- ssc_p: средневзвешенный балл ученика в школе
- ssc_b: название школы (central - школа при университете, others - другие)
- hsc_p: средневзвешенный балл в университете 
- hsc_b: название университета (central - основной университет, others - другие)
- hsc_s: специализация высшего образования
- degree_p: средневзвешенная оценка по специализации 
- degree_t: специализация выпускника
- workex: наличие опыта работы
- etest_p: оценка за тест по трудоустройству
- specialization: область магистратуры
- mba_p: средневзвешенная оценка за магистратуру
- status: статус трудоустройства (placed - работа была предложена, not placed - предложение не получено)
- salary: зарплата, предложенная кандидату


**Перед отправкой убедитесь в том, что в начале документа правильно указаны ваша фамилия и вариант.**
