---
title: "Методы экспоненциального сглаживания"
author: "<ваше имя>"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Введение

В этом задании необходимо построить несколько моделей прогнозирования для различных макроэкономических показателей из ЕАЭСД (sophist). 

Выполните пункты задания, перечисленные ниже и ответьте на поставленные в задании вопросы.

Решения присылайте в HTML-формате на `postlogist@gmail.com`.

Задание можно делать в небольших группах (2-3 человека). Не забудьте указать авторов в заголовке документа.

------

# Задания


## 1. Прогноз численности населения России методом экспоненциального сглаживания

1. Загрузите из EАЭСД (sophist) ряд с годовыми показателями численности населения России (`POPNUM_Y`).  
2. Используя метод простого экспоненциального сглаживания, постройте прогноз численности населения на 5 лет (константу сглаживания не задавайте, она будет подобрана автоматически).  
3. Выведите и проанализируйте сводку по модели (`summary()`):  
   - Чему равна константа сглаживания?  
   - Интерпретируйте показатели ошибки.  
4. Визуализируйте прогноз и значения уровня ряда в историческом периоде.  
5. Попробуйте задать несколько различных значений константы сглаживания. Как это влияет на уровень ряда и прогноз?  
6. Можно ли доверять прогнозу? Почему?  


## 2. Прогноз численности населения России методом Хольта

1. Продолжите работу с годовыми показателями численности населения России (`POPNUM_Y`). Используя метод Хольта, постройте прогноз численности населения на 5 лет (константы сглаживания не задавайте, они будут подобраны автоаматически).  
2. Выведите и проанализируйте сводку по модели (`summary()`):  
   - Чему равны константы сглаживания?  
   - Интерпретируйте показатели ошибки и сравните их с ошибками метода простого экспоненциального сглаживания.  
3. Визуализируйте прогноз и значения уровня ряда в историческом периоде.  
4. Попробуйте задать несколько различных значений констант сглаживания. Как это влияет на компоненты ряда и прогноз?  
5. Можно ли доверять прогнозу? Почему?  



## 3. Прогнозирование индекса пассажирооборота транспорта общего пользования

1. Загрузите из EАЭСД (sophist) ряд с месячными показателями индекса пассажирооборота транспорта общего пользования (`TRP_M_PASS_DIRI`).  
2. Визуализируйте ряд и изучите структуру его закономерных компонентов. Когда наблюдаются периоды повышенного спроса на пассажирские перевозки? Чем это обусловлено? Какой это тип сезонности?  
3. Как кризисы повлияли на тренд пассажироооборота? Что при этом произошло с сезонным компонентом?
4. На основе ваших выводов о структуре ряда, выберите подходящую модель прогнозирования.  
5. Надо ли ограничивать глубину исторического периода при построении модели, или следует взять все данные?  
6. Методом Ex-Post прогнозирования сравните 2-3 варианта модели, различающиеся типом сезонности и/или значениями констант. В качестве тестового периода используйте последние 12 месяцев от имеющихся данных. Сравнение необходимо провести визуальным методом и с помощью показателей ошибок.   
7. Выберите лучшую модель и постройте модель с такими же параметрами, использующую актуальные данные о пассажирообороте (т.е. теперь тестовый период исключать не нужно). С помощью полученной модели сделайте прогноз пассажирооборота на 2 года вперед.  
8. При помощи метода скользящего контроля оцените стандартную ошибку прогноза на горизонте 1, 3, 6, 12 и 24 месяцев.  
