---
title: "Сравнение экзаменаторов"
author: "Студент школы логистики, не умеющий править тег `author`"
output: 
  html_document: 
    toc: yes
---


```{r Настройка, include=TRUE}
knitr::opts_chunk$set(dev = 'png', warning = FALSE) 
# выбор формата для графиков и отключение жалоб на русские шрифты на графиках
options(digits = 4) # Количество значащих цифр при выводе
suppressMessages(library(readr))
suppressMessages(library(tidyverse))
suppressMessages(library(ggplot2))
```


## Постановка задачи

В файле `markers.txt` содержатся исходные данные о результатах проверки работ абитуриентов двумя экзаменаторами. В первом столбце содержится номер абитуриента, во 2-м и 3-м - соответственно, балл за работу, поставленный экзаменаторами А и Б. Наихудшим результатом является 0, а наилучшим - 4.

Требуется с помощью разведочного анализа сравнить оценки, выставленные двумя экзаменаторами. С использованием подходящего t-критерия проверьте гипотезу о том, что требования экзаменаторов являются сходными и, в среднем, их оценки не отличаются.

# Здесь ваше решение

...

# Как сдавать

Результатом вашей работы является отчет в формате HTML, полученный с помощью кнопки Knit из данного файла.

Отредактируйте тег `author:` в начале этого документа, указав свою фамилию (фамилии) и группу.

Решения присылайте на мой email.
