---
title: "Исследование данных о предприятиях общественного питания Москвы"
author: "Здесь должна быть ваша фамилия"
date: '19 октября 2017 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

#Описание набора данных

Набор данных [caterings.xlsx](data/caterings.xlsx) загружен с [Портала открытых данных Правительства Москвы](https://data.mos.ru/opendata/7710881420-obshchestvennoe-pitanie-v-moskve) и содержит информацию о расположении предприятий общественного питания города Москвы.

Файл данных имеет следующие поля:

- Код - код предприятия;

- global_id - глобальный идентификатор предприятия; 

- Наименование - наименование предприятия;

- Является сетевым - признак (да/нет), является ли предприятие сетевым;

- Название управляющей компании (если предприятие является сетевым);

- Вид объекта - вид предприятия общественного питания (кафе, столовая и др.);

- Административный округ, в котором находится предприятие;

- Район, в котором находится предприятие;

- Адрес - адрес предприятия;

- Контактный телефон;

- Число посадочных мест;

- Показатель социальных льгот - признак, имеются ли социальные льготы (да/нет);

- Долгота в WGS-84 - географическая долгота месторасположения предприятия;

- Широта в WGS-84 - географическая широта месторасположения предприятия;

- Геоданные - координаты расположения предприятия.
