---
title: "Исследование всемирного уровня счастья"
author: Здесь должна быть ваша фамилия
date: '19 октября 2017 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Описание набора данных

Набор данных [happiness.csv](data/happiness.csv) загружен c сайта [kaggle.com](https://www.kaggle.com/unsdsn/world-happiness/downloads/2016.csv) и содержит информацию, полученную в ходе глобального исследования уровня счастья "The World Happiness" в 2016 году. Усредненные оценки различным показателям по странам были собраны в ходе опроса респондентов. Респонденты должны были оценить тот или иной фактор своей жизни по десятибалльной шкале, в которой 0 соответствовало наихудшему положению дел, а 10 - наилучшему. Для целей сравнения была придумана несуществующая страна Дистопия, все показатели которой соответствуют наихудшему значению из полученных усредненных значений по странам (т.е. наихудшее значение в каждом столбце).

В файле данных содержатся переменные:

  - Country - страна;
  
  - Region - регион, в который входит страна;
  
  - Happiness Rank - уровень счастья (рейтинг);
  
  - Happiness Score - усредненная оценка ответов респондентов на вопрос "Как бы вы оценили свой уровень счастья по 10-балльной шкале, где 10 - самый счастливый?"

  - Lower Confidence Interval - нижняя граница доверительного интервала уровня счастья;

  - Upper Confidence Interval - верхняя граница доверительного интервала уровня счастья;

  - Economy (GDP per Capita) - состояние экономики (ВВП на душу населения);

  - Family - субъективная оценка влияния семьи на уровень счастья респондента;

  - Health (Life Expectancy) - здоровье (продолжительность жизни) - мера, в которой продолжительность жизни оказывает влияние на уровень счастья;

  - Freedom - мера, в которой свобода оказывает влияние на уровень счастья;

  - Trust (Government Corruption) - доверие (коррупция в государстве) - мера, в которой восприятие коррупции оказывает влияние на уровень счастья;

  - Generosity - мера, в которой великодушие, щедрость оказывают влияние на уровень счастья;
  
  - Dystopia Residual - остаток, получившийся при вычитании показателя Дистопии.


