---
title: "Исследование данных о платных парковках города Москвы"
author: "Здесь должна быть ваша фамилия"
date: '19 октября 2017 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

#Описание набора данных

Набор данных [parkings.zip](data/parkings.zip) загружен с [Портала открытых данных Правительства Москвы](https://data.mos.ru/opendata/7704786030-platnye-parkovki-na-ulichno-dorojnoy-seti) и содержит информацию о платных парковках города Москвы, их местоположении на карте, точный адрес расположения, режим работы, стоимость одного часа парковки, а также количество парковочных мест.

В наборе данных имеются следующие столбцы:

- ID - идентификатор парковки;  	

- ParkingName	- название парковки;  

- global_id	- глобальный идентификатор; 

- ParkingZoneNumber	- номер зоны;  

- AdmArea	- административный округ;  

- District - район города;  

- Address	- адрес парковки;  

- WorkingHours - часы работы парковки;  

- Price	- стоимость парковки (руб. в час); 

- CarCapacity	- количество парковочных мест; 

- Longitude_WGS84	- географическая долгота центра парковки;

- Latitude_WGS84 - географическая широта центра парковки; 

- Coordinates	- координаты парковки;  

- geoData - геоданные о парковке.


