---
title: "Исследование данных о рейтинге университетов"
author: Здесь должна быть ваша фамилия
date: '19 октября 2017 г '
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Описание набора данных

Набор данных [cwurData.csv](data/cwurData.csv) загружен с сайта [kaggle.com](https://www.kaggle.com/mylesoneill/world-university-rankings/downloads/cwurData.csv) и содержит информацию, полученную в ходе рейтингования университетов, проведенного организацией [The Center for World University Rankings](http://cwur.org/), основанной в Саудовской Аравии.

В наборе данных содержатся переменные:

  - world_rank - место в мировом рейтинге;

  - institution - название университета;
  
  - country - страна университета;

  - national_rank - место в национальном рейтинге;

  - quality_of_education - место по качеству образования;
  
  - alumni_employment - место по трудоустройству выпускников;

  - quality_of_faculty - место по качеству профессорско-преподавательского состава;

  - publications - место по количеству публикаций;

  - influence - место по силле влияния;
  
  - citations - место по цитируемости;
  
  - broad_impact - место по региональному влиянию (только в 2014-2015 гг.);

  - patents - место по количеству патентов;
  
  - score - общая оценка для рейтингования;
  
  - year - год рейтингования (2012-2015).
